# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/psptracker/forms/AbstractOfflineTracker.ui'
#
# Created: Sat Sep 12 19:13:31 2009
#      by: PyQt4 UI code generator 4.5.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_AbstractOfflineTracker(object):
    def setupUi(self, AbstractOfflineTracker):
        AbstractOfflineTracker.setObjectName("AbstractOfflineTracker")
        AbstractOfflineTracker.resize(492, 463)
        self.gridlayout = QtGui.QGridLayout(AbstractOfflineTracker)
        self.gridlayout.setObjectName("gridlayout")
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.pushButton11 = QtGui.QPushButton(AbstractOfflineTracker)
        self.pushButton11.setObjectName("pushButton11")
        self.hboxlayout.addWidget(self.pushButton11)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.pushButton12 = QtGui.QPushButton(AbstractOfflineTracker)
        self.pushButton12.setObjectName("pushButton12")
        self.hboxlayout.addWidget(self.pushButton12)
        spacerItem1 = QtGui.QSpacerItem(16, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem1)
        self.pushButton13 = QtGui.QPushButton(AbstractOfflineTracker)
        self.pushButton13.setObjectName("pushButton13")
        self.hboxlayout.addWidget(self.pushButton13)
        spacerItem2 = QtGui.QSpacerItem(51, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem2)
        self.pushButton10 = QtGui.QPushButton(AbstractOfflineTracker)
        self.pushButton10.setObjectName("pushButton10")
        self.hboxlayout.addWidget(self.pushButton10)
        self.pushButton9 = QtGui.QPushButton(AbstractOfflineTracker)
        self.pushButton9.setObjectName("pushButton9")
        self.hboxlayout.addWidget(self.pushButton9)
        self.gridlayout.addLayout(self.hboxlayout, 0, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem3, 1, 0, 1, 1)
        self.gridlayout1 = QtGui.QGridLayout()
        self.gridlayout1.setObjectName("gridlayout1")
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.LabelActivity = QtGui.QLabel(AbstractOfflineTracker)
        self.LabelActivity.setWordWrap(False)
        self.LabelActivity.setObjectName("LabelActivity")
        self.hboxlayout1.addWidget(self.LabelActivity)
        spacerItem4 = QtGui.QSpacerItem(101, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem4)
        self.gridlayout1.addLayout(self.hboxlayout1, 0, 0, 1, 1)
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.Category = QtGui.QComboBox(AbstractOfflineTracker)
        self.Category.setObjectName("Category")
        self.hboxlayout2.addWidget(self.Category)
        self.Activity = QtGui.QComboBox(AbstractOfflineTracker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Activity.sizePolicy().hasHeightForWidth())
        self.Activity.setSizePolicy(sizePolicy)
        self.Activity.setAutoCompletion(True)
        self.Activity.setObjectName("Activity")
        self.hboxlayout2.addWidget(self.Activity)
        self.ActivityManagement = QtGui.QToolButton(AbstractOfflineTracker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ActivityManagement.sizePolicy().hasHeightForWidth())
        self.ActivityManagement.setSizePolicy(sizePolicy)
        self.ActivityManagement.setObjectName("ActivityManagement")
        self.hboxlayout2.addWidget(self.ActivityManagement)
        self.gridlayout1.addLayout(self.hboxlayout2, 1, 0, 1, 1)
        self.gridlayout.addLayout(self.gridlayout1, 2, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(21, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem5, 3, 0, 1, 1)
        self.vboxlayout = QtGui.QVBoxLayout()
        self.vboxlayout.setObjectName("vboxlayout")
        self.hboxlayout3 = QtGui.QHBoxLayout()
        self.hboxlayout3.setObjectName("hboxlayout3")
        self.LabelDescription = QtGui.QLabel(AbstractOfflineTracker)
        self.LabelDescription.setWordWrap(False)
        self.LabelDescription.setObjectName("LabelDescription")
        self.hboxlayout3.addWidget(self.LabelDescription)
        spacerItem6 = QtGui.QSpacerItem(81, 21, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout3.addItem(spacerItem6)
        self.vboxlayout.addLayout(self.hboxlayout3)
        self.gridlayout.addLayout(self.vboxlayout, 4, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem7, 6, 0, 1, 1)
        self.hboxlayout4 = QtGui.QHBoxLayout()
        self.hboxlayout4.setObjectName("hboxlayout4")
        spacerItem8 = QtGui.QSpacerItem(60, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout4.addItem(spacerItem8)
        self.vboxlayout1 = QtGui.QVBoxLayout()
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.LabelStart = QtGui.QLabel(AbstractOfflineTracker)
        self.LabelStart.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LabelStart.setWordWrap(False)
        self.LabelStart.setObjectName("LabelStart")
        self.vboxlayout1.addWidget(self.LabelStart)
        self.LabelEnd = QtGui.QLabel(AbstractOfflineTracker)
        self.LabelEnd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LabelEnd.setWordWrap(False)
        self.LabelEnd.setObjectName("LabelEnd")
        self.vboxlayout1.addWidget(self.LabelEnd)
        self.LabelTime = QtGui.QLabel(AbstractOfflineTracker)
        self.LabelTime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LabelTime.setWordWrap(False)
        self.LabelTime.setObjectName("LabelTime")
        self.vboxlayout1.addWidget(self.LabelTime)
        self.hboxlayout4.addLayout(self.vboxlayout1)
        self.vboxlayout2 = QtGui.QVBoxLayout()
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.dateTimeStart = QtGui.QDateTimeEdit(AbstractOfflineTracker)
        self.dateTimeStart.setObjectName("dateTimeStart")
        self.vboxlayout2.addWidget(self.dateTimeStart)
        self.dateTimeEnd = QtGui.QDateTimeEdit(AbstractOfflineTracker)
        self.dateTimeEnd.setObjectName("dateTimeEnd")
        self.vboxlayout2.addWidget(self.dateTimeEnd)
        self.hboxlayout5 = QtGui.QHBoxLayout()
        self.hboxlayout5.setObjectName("hboxlayout5")
        self.timeTotal = QtGui.QTimeEdit(AbstractOfflineTracker)
        self.timeTotal.setObjectName("timeTotal")
        self.hboxlayout5.addWidget(self.timeTotal)
        spacerItem9 = QtGui.QSpacerItem(71, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout5.addItem(spacerItem9)
        self.vboxlayout2.addLayout(self.hboxlayout5)
        self.hboxlayout4.addLayout(self.vboxlayout2)
        spacerItem10 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout4.addItem(spacerItem10)
        self.gridlayout.addLayout(self.hboxlayout4, 7, 0, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(20, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem11, 8, 0, 1, 1)
        self.textDescription = QtGui.QTextEdit(AbstractOfflineTracker)
        self.textDescription.setObjectName("textDescription")
        self.gridlayout.addWidget(self.textDescription, 5, 0, 1, 1)

        self.retranslateUi(AbstractOfflineTracker)
        QtCore.QMetaObject.connectSlotsByName(AbstractOfflineTracker)

    def retranslateUi(self, AbstractOfflineTracker):
        AbstractOfflineTracker.setWindowTitle(QtGui.QApplication.translate("AbstractOfflineTracker", "Offline Tracker", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton11.setText(QtGui.QApplication.translate("AbstractOfflineTracker", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton12.setText(QtGui.QApplication.translate("AbstractOfflineTracker", "Erase", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton13.setText(QtGui.QApplication.translate("AbstractOfflineTracker", "Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton10.setText(QtGui.QApplication.translate("AbstractOfflineTracker", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton9.setText(QtGui.QApplication.translate("AbstractOfflineTracker", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelActivity.setText(QtGui.QApplication.translate("AbstractOfflineTracker", "Activity", None, QtGui.QApplication.UnicodeUTF8))
        self.ActivityManagement.setText(QtGui.QApplication.translate("AbstractOfflineTracker", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelDescription.setText(QtGui.QApplication.translate("AbstractOfflineTracker", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelStart.setText(QtGui.QApplication.translate("AbstractOfflineTracker", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelEnd.setText(QtGui.QApplication.translate("AbstractOfflineTracker", "End", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelTime.setText(QtGui.QApplication.translate("AbstractOfflineTracker", "Total time", None, QtGui.QApplication.UnicodeUTF8))

